#pragma once

typedef enum
{
    CPPIE_SCANCODE_UNKNOWN = 0,

    /** 
     *  \name Usage page 0x07
     *  
     *  These values are from usage page 0x07 (USB keyboard page).
     */
    /*@{*/

    CPPIE_SCANCODE_A = 4,
    CPPIE_SCANCODE_B = 5,
    CPPIE_SCANCODE_C = 6,
    CPPIE_SCANCODE_D = 7,
    CPPIE_SCANCODE_E = 8,
    CPPIE_SCANCODE_F = 9,
    CPPIE_SCANCODE_G = 10,
    CPPIE_SCANCODE_H = 11,
    CPPIE_SCANCODE_I = 12,
    CPPIE_SCANCODE_J = 13,
    CPPIE_SCANCODE_K = 14,
    CPPIE_SCANCODE_L = 15,
    CPPIE_SCANCODE_M = 16,
    CPPIE_SCANCODE_N = 17,
    CPPIE_SCANCODE_O = 18,
    CPPIE_SCANCODE_P = 19,
    CPPIE_SCANCODE_Q = 20,
    CPPIE_SCANCODE_R = 21,
    CPPIE_SCANCODE_S = 22,
    CPPIE_SCANCODE_T = 23,
    CPPIE_SCANCODE_U = 24,
    CPPIE_SCANCODE_V = 25,
    CPPIE_SCANCODE_W = 26,
    CPPIE_SCANCODE_X = 27,
    CPPIE_SCANCODE_Y = 28,
    CPPIE_SCANCODE_Z = 29,

    CPPIE_SCANCODE_1 = 30,
    CPPIE_SCANCODE_2 = 31,
    CPPIE_SCANCODE_3 = 32,
    CPPIE_SCANCODE_4 = 33,
    CPPIE_SCANCODE_5 = 34,
    CPPIE_SCANCODE_6 = 35,
    CPPIE_SCANCODE_7 = 36,
    CPPIE_SCANCODE_8 = 37,
    CPPIE_SCANCODE_9 = 38,
    CPPIE_SCANCODE_0 = 39,

    CPPIE_SCANCODE_RETURN = 40,
    CPPIE_SCANCODE_ESCAPE = 41,
    CPPIE_SCANCODE_BACKSPACE = 42,
    CPPIE_SCANCODE_TAB = 43,
    CPPIE_SCANCODE_SPACE = 44,

    CPPIE_SCANCODE_MINUS = 45,
    CPPIE_SCANCODE_EQUALS = 46,
    CPPIE_SCANCODE_LEFTBRACKET = 47,
    CPPIE_SCANCODE_RIGHTBRACKET = 48,
    CPPIE_SCANCODE_BACKSLASH = 49, /**< Located at the lower left of the return 
                                  *   key on ISO keyboards and at the right end 
                                  *   of the QWERTY row on ANSI keyboards. 
                                  *   Produces REVERSE SOLIDUS (backslash) and 
                                  *   VERTICAL LINE in a US layout, REVERSE 
                                  *   SOLIDUS and VERTICAL LINE in a UK Mac 
                                  *   layout, NUMBER SIGN and TILDE in a UK 
                                  *   Windows layout, DOLLAR SIGN and POUND SIGN
                                  *   in a Swiss German layout, NUMBER SIGN and 
                                  *   APOSTROPHE in a German layout, GRAVE 
                                  *   ACCENT and POUND SIGN in a French Mac 
                                  *   layout, and ASTERISK and MICRO SIGN in a 
                                  *   French Windows layout.
                                  */
    CPPIE_SCANCODE_NONUSHASH = 50, /**< ISO USB keyboards actually use this code 
                                  *   instead of 49 for the same key, but all 
                                  *   OSes I've seen treat the two codes 
                                  *   identically. So, as an implementor, unless
                                  *   your keyboard generates both of those 
                                  *   codes and your OS treats them differently,
                                  *   you should generate CPPIE_SCANCODE_BACKSLASH
                                  *   instead of this code. As a user, you 
                                  *   should not rely on this code because CPPIE 
                                  *   will never generate it with most (all?) 
                                  *   keyboards. 
                                  */
    CPPIE_SCANCODE_SEMICOLON = 51,
    CPPIE_SCANCODE_APOSTROPHE = 52,
    CPPIE_SCANCODE_GRAVE = 53, /**< Located in the top left corner (on both ANSI 
                              *   and ISO keyboards). Produces GRAVE ACCENT and 
                              *   TILDE in a US Windows layout and in US and UK 
                              *   Mac layouts on ANSI keyboards, GRAVE ACCENT 
                              *   and NOT SIGN in a UK Windows layout, SECTION 
                              *   SIGN and PLUS-MINUS SIGN in US and UK Mac 
                              *   layouts on ISO keyboards, SECTION SIGN and 
                              *   DEGREE SIGN in a Swiss German layout (Mac: 
                              *   only on ISO keyboards), CIRCUMFLEX ACCENT and 
                              *   DEGREE SIGN in a German layout (Mac: only on 
                              *   ISO keyboards), SUPERSCRIPT TWO and TILDE in a
                              *   French Windows layout, COMMERCIAL AT and 
                              *   NUMBER SIGN in a French Mac layout on ISO 
                              *   keyboards, and LESS-THAN SIGN and GREATER-THAN
                              *   SIGN in a Swiss German, German, or French Mac 
                              *   layout on ANSI keyboards.
                              */
    CPPIE_SCANCODE_COMMA = 54,
    CPPIE_SCANCODE_PERIOD = 55,
    CPPIE_SCANCODE_SLASH = 56,

    CPPIE_SCANCODE_CAPSLOCK = 57,

    CPPIE_SCANCODE_F1 = 58,
    CPPIE_SCANCODE_F2 = 59,
    CPPIE_SCANCODE_F3 = 60,
    CPPIE_SCANCODE_F4 = 61,
    CPPIE_SCANCODE_F5 = 62,
    CPPIE_SCANCODE_F6 = 63,
    CPPIE_SCANCODE_F7 = 64,
    CPPIE_SCANCODE_F8 = 65,
    CPPIE_SCANCODE_F9 = 66,
    CPPIE_SCANCODE_F10 = 67,
    CPPIE_SCANCODE_F11 = 68,
    CPPIE_SCANCODE_F12 = 69,

    CPPIE_SCANCODE_PRINTSCREEN = 70,
    CPPIE_SCANCODE_SCROLLLOCK = 71,
    CPPIE_SCANCODE_PAUSE = 72,
    CPPIE_SCANCODE_INSERT = 73, /**< insert on PC, help on some Mac keyboards (but
                                   does send code 73, not 117) */
    CPPIE_SCANCODE_HOME = 74,
    CPPIE_SCANCODE_PAGEUP = 75,
    CPPIE_SCANCODE_DELETE = 76,
    CPPIE_SCANCODE_END = 77,
    CPPIE_SCANCODE_PAGEDOWN = 78,
    CPPIE_SCANCODE_RIGHT = 79,
    CPPIE_SCANCODE_LEFT = 80,
    CPPIE_SCANCODE_DOWN = 81,
    CPPIE_SCANCODE_UP = 82,

    CPPIE_SCANCODE_NUMLOCKCLEAR = 83, /**< num lock on PC, clear on Mac keyboards 
                                     */
    CPPIE_SCANCODE_KP_DIVIDE = 84,
    CPPIE_SCANCODE_KP_MULTIPLY = 85,
    CPPIE_SCANCODE_KP_MINUS = 86,
    CPPIE_SCANCODE_KP_PLUS = 87,
    CPPIE_SCANCODE_KP_ENTER = 88,
    CPPIE_SCANCODE_KP_1 = 89,
    CPPIE_SCANCODE_KP_2 = 90,
    CPPIE_SCANCODE_KP_3 = 91,
    CPPIE_SCANCODE_KP_4 = 92,
    CPPIE_SCANCODE_KP_5 = 93,
    CPPIE_SCANCODE_KP_6 = 94,
    CPPIE_SCANCODE_KP_7 = 95,
    CPPIE_SCANCODE_KP_8 = 96,
    CPPIE_SCANCODE_KP_9 = 97,
    CPPIE_SCANCODE_KP_0 = 98,
    CPPIE_SCANCODE_KP_PERIOD = 99,

    CPPIE_SCANCODE_NONUSBACKSLASH = 100, /**< This is the additional key that ISO 
                                        *   keyboards have over ANSI ones, 
                                        *   located between left shift and Y. 
                                        *   Produces GRAVE ACCENT and TILDE in a
                                        *   US or UK Mac layout, REVERSE SOLIDUS
                                        *   (backslash) and VERTICAL LINE in a 
                                        *   US or UK Windows layout, and 
                                        *   LESS-THAN SIGN and GREATER-THAN SIGN
                                        *   in a Swiss German, German, or French
                                        *   layout. */
    CPPIE_SCANCODE_APPLICATION = 101, /**< windows contextual menu, compose */
    CPPIE_SCANCODE_POWER = 102, /**< The USB document says this is a status flag, 
                               *   not a physical key - but some Mac keyboards 
                               *   do have a power key. */
    CPPIE_SCANCODE_KP_EQUALS = 103,
    CPPIE_SCANCODE_F13 = 104,
    CPPIE_SCANCODE_F14 = 105,
    CPPIE_SCANCODE_F15 = 106,
    CPPIE_SCANCODE_F16 = 107,
    CPPIE_SCANCODE_F17 = 108,
    CPPIE_SCANCODE_F18 = 109,
    CPPIE_SCANCODE_F19 = 110,
    CPPIE_SCANCODE_F20 = 111,
    CPPIE_SCANCODE_F21 = 112,
    CPPIE_SCANCODE_F22 = 113,
    CPPIE_SCANCODE_F23 = 114,
    CPPIE_SCANCODE_F24 = 115,
    CPPIE_SCANCODE_EXECUTE = 116,
    CPPIE_SCANCODE_HELP = 117,
    CPPIE_SCANCODE_MENU = 118,
    CPPIE_SCANCODE_SELECT = 119,
    CPPIE_SCANCODE_STOP = 120,
    CPPIE_SCANCODE_AGAIN = 121,   /**< redo */
    CPPIE_SCANCODE_UNDO = 122,
    CPPIE_SCANCODE_CUT = 123,
    CPPIE_SCANCODE_COPY = 124,
    CPPIE_SCANCODE_PASTE = 125,
    CPPIE_SCANCODE_FIND = 126,
    CPPIE_SCANCODE_MUTE = 127,
    CPPIE_SCANCODE_VOLUMEUP = 128,
    CPPIE_SCANCODE_VOLUMEDOWN = 129,
/* not sure whether there's a reason to enable these */
/*     CPPIE_SCANCODE_LOCKINGCAPSLOCK = 130,  */
/*     CPPIE_SCANCODE_LOCKINGNUMLOCK = 131, */
/*     CPPIE_SCANCODE_LOCKINGSCROLLLOCK = 132, */
    CPPIE_SCANCODE_KP_COMMA = 133,
    CPPIE_SCANCODE_KP_EQUALSAS400 = 134,

    CPPIE_SCANCODE_INTERNATIONAL1 = 135, /**< used on Asian keyboards, see 
                                            footnotes in USB doc */
    CPPIE_SCANCODE_INTERNATIONAL2 = 136,
    CPPIE_SCANCODE_INTERNATIONAL3 = 137, /**< Yen */
    CPPIE_SCANCODE_INTERNATIONAL4 = 138,
    CPPIE_SCANCODE_INTERNATIONAL5 = 139,
    CPPIE_SCANCODE_INTERNATIONAL6 = 140,
    CPPIE_SCANCODE_INTERNATIONAL7 = 141,
    CPPIE_SCANCODE_INTERNATIONAL8 = 142,
    CPPIE_SCANCODE_INTERNATIONAL9 = 143,
    CPPIE_SCANCODE_LANG1 = 144, /**< Hangul/English toggle */
    CPPIE_SCANCODE_LANG2 = 145, /**< Hanja conversion */
    CPPIE_SCANCODE_LANG3 = 146, /**< Katakana */
    CPPIE_SCANCODE_LANG4 = 147, /**< Hiragana */
    CPPIE_SCANCODE_LANG5 = 148, /**< Zenkaku/Hankaku */
    CPPIE_SCANCODE_LANG6 = 149, /**< reserved */
    CPPIE_SCANCODE_LANG7 = 150, /**< reserved */
    CPPIE_SCANCODE_LANG8 = 151, /**< reserved */
    CPPIE_SCANCODE_LANG9 = 152, /**< reserved */

    CPPIE_SCANCODE_ALTERASE = 153, /**< Erase-Eaze */
    CPPIE_SCANCODE_SYSREQ = 154,
    CPPIE_SCANCODE_CANCEL = 155,
    CPPIE_SCANCODE_CLEAR = 156,
    CPPIE_SCANCODE_PRIOR = 157,
    CPPIE_SCANCODE_RETURN2 = 158,
    CPPIE_SCANCODE_SEPARATOR = 159,
    CPPIE_SCANCODE_OUT = 160,
    CPPIE_SCANCODE_OPER = 161,
    CPPIE_SCANCODE_CLEARAGAIN = 162,
    CPPIE_SCANCODE_CRSEL = 163,
    CPPIE_SCANCODE_EXSEL = 164,

    CPPIE_SCANCODE_KP_00 = 176,
    CPPIE_SCANCODE_KP_000 = 177,
    CPPIE_SCANCODE_THOUSANDSSEPARATOR = 178,
    CPPIE_SCANCODE_DECIMALSEPARATOR = 179,
    CPPIE_SCANCODE_CURRENCYUNIT = 180,
    CPPIE_SCANCODE_CURRENCYSUBUNIT = 181,
    CPPIE_SCANCODE_KP_LEFTPAREN = 182,
    CPPIE_SCANCODE_KP_RIGHTPAREN = 183,
    CPPIE_SCANCODE_KP_LEFTBRACE = 184,
    CPPIE_SCANCODE_KP_RIGHTBRACE = 185,
    CPPIE_SCANCODE_KP_TAB = 186,
    CPPIE_SCANCODE_KP_BACKSPACE = 187,
    CPPIE_SCANCODE_KP_A = 188,
    CPPIE_SCANCODE_KP_B = 189,
    CPPIE_SCANCODE_KP_C = 190,
    CPPIE_SCANCODE_KP_D = 191,
    CPPIE_SCANCODE_KP_E = 192,
    CPPIE_SCANCODE_KP_F = 193,
    CPPIE_SCANCODE_KP_XOR = 194,
    CPPIE_SCANCODE_KP_POWER = 195,
    CPPIE_SCANCODE_KP_PERCENT = 196,
    CPPIE_SCANCODE_KP_LESS = 197,
    CPPIE_SCANCODE_KP_GREATER = 198,
    CPPIE_SCANCODE_KP_AMPERSAND = 199,
    CPPIE_SCANCODE_KP_DBLAMPERSAND = 200,
    CPPIE_SCANCODE_KP_VERTICALBAR = 201,
    CPPIE_SCANCODE_KP_DBLVERTICALBAR = 202,
    CPPIE_SCANCODE_KP_COLON = 203,
    CPPIE_SCANCODE_KP_HASH = 204,
    CPPIE_SCANCODE_KP_SPACE = 205,
    CPPIE_SCANCODE_KP_AT = 206,
    CPPIE_SCANCODE_KP_EXCLAM = 207,
    CPPIE_SCANCODE_KP_MEMSTORE = 208,
    CPPIE_SCANCODE_KP_MEMRECALL = 209,
    CPPIE_SCANCODE_KP_MEMCLEAR = 210,
    CPPIE_SCANCODE_KP_MEMADD = 211,
    CPPIE_SCANCODE_KP_MEMSUBTRACT = 212,
    CPPIE_SCANCODE_KP_MEMMULTIPLY = 213,
    CPPIE_SCANCODE_KP_MEMDIVIDE = 214,
    CPPIE_SCANCODE_KP_PLUSMINUS = 215,
    CPPIE_SCANCODE_KP_CLEAR = 216,
    CPPIE_SCANCODE_KP_CLEARENTRY = 217,
    CPPIE_SCANCODE_KP_BINARY = 218,
    CPPIE_SCANCODE_KP_OCTAL = 219,
    CPPIE_SCANCODE_KP_DECIMAL = 220,
    CPPIE_SCANCODE_KP_HEXADECIMAL = 221,

    CPPIE_SCANCODE_LCTRL = 224,
    CPPIE_SCANCODE_LSHIFT = 225,
    CPPIE_SCANCODE_LALT = 226, /**< alt, option */
    CPPIE_SCANCODE_LGUI = 227, /**< windows, command (apple), meta */
    CPPIE_SCANCODE_RCTRL = 228,
    CPPIE_SCANCODE_RSHIFT = 229,
    CPPIE_SCANCODE_RALT = 230, /**< alt gr, option */
    CPPIE_SCANCODE_RGUI = 231, /**< windows, command (apple), meta */

    CPPIE_SCANCODE_MODE = 257,    /**< I'm not sure if this is really not covered 
                                 *   by any of the above, but since there's a 
                                 *   special KMOD_MODE for it I'm adding it here
                                 */
    
    /*@}*//*Usage page 0x07*/

    /**
     *  \name Usage page 0x0C
     *  
     *  These values are mapped from usage page 0x0C (USB consumer page).
     */
    /*@{*/

    CPPIE_SCANCODE_AUDIONEXT = 258,
    CPPIE_SCANCODE_AUDIOPREV = 259,
    CPPIE_SCANCODE_AUDIOSTOP = 260,
    CPPIE_SCANCODE_AUDIOPLAY = 261,
    CPPIE_SCANCODE_AUDIOMUTE = 262,
    CPPIE_SCANCODE_MEDIASELECT = 263,
    CPPIE_SCANCODE_WWW = 264,
    CPPIE_SCANCODE_MAIL = 265,
    CPPIE_SCANCODE_CALCULATOR = 266,
    CPPIE_SCANCODE_COMPUTER = 267,
    CPPIE_SCANCODE_AC_SEARCH = 268,
    CPPIE_SCANCODE_AC_HOME = 269,
    CPPIE_SCANCODE_AC_BACK = 270,
    CPPIE_SCANCODE_AC_FORWARD = 271,
    CPPIE_SCANCODE_AC_STOP = 272,
    CPPIE_SCANCODE_AC_REFRESH = 273,
    CPPIE_SCANCODE_AC_BOOKMARKS = 274,
    
    /*@}*//*Usage page 0x0C*/

    /**
     *  \name Walther keys
     *  
     *  These are values that Christian Walther added (for mac keyboard?).
     */
    /*@{*/

    CPPIE_SCANCODE_BRIGHTNESSDOWN = 275,
    CPPIE_SCANCODE_BRIGHTNESSUP = 276,
    CPPIE_SCANCODE_DISPLAYSWITCH = 277, /**< display mirroring/dual display 
                                           switch, video mode switch */
    CPPIE_SCANCODE_KBDILLUMTOGGLE = 278,
    CPPIE_SCANCODE_KBDILLUMDOWN = 279,
    CPPIE_SCANCODE_KBDILLUMUP = 280,
    CPPIE_SCANCODE_EJECT = 281,
    CPPIE_SCANCODE_SLEEP = 282,
    
	CPPIE_SCANCODE_APP1 = 283,
	CPPIE_SCANCODE_APP2 = 284,

    /*@}*//*Walther keys*/

    /* Add any other keys here. */

    CPPIE_NUM_SCANCODES = 512 /**< not a key, just marks the number of scancodes 
                                 for array bounds */
} CPPIE_Scancode;


#define CPPIE_SCANCODE_MASK (1<<30)
#define CPPIE_SCANCODE_TO_KEYCODE(X)	(X | CPPIE_SCANCODE_MASK)

enum
{
    CPPIE_UNKNOWN = 0,

    CPPIE_RETURN = '\r',
    CPPIE_ESCAPE = '\033',
    CPPIE_BACKSPACE = '\b',
    CPPIE_TAB = '\t',
    CPPIE_SPACE = ' ',
    CPPIE_EXCLAIM = '!',
    CPPIE_QUOTEDBL = '"',
    CPPIE_HASH = '#',
    CPPIE_PERCENT = '%',
    CPPIE_DOLLAR = '$',
    CPPIE_AMPERSAND = '&',
    CPPIE_QUOTE = '\'',
    CPPIE_LEFTPAREN = '(',
    CPPIE_RIGHTPAREN = ')',
    CPPIE_ASTERISK = '*',
    CPPIE_PLUS = '+',
    CPPIE_COMMA = ',',
    CPPIE_MINUS = '-',
    CPPIE_PERIOD = '.',
    CPPIE_SLASH = '/',
    CPPIE_0 = '0',
    CPPIE_1 = '1',
    CPPIE_2 = '2',
    CPPIE_3 = '3',
    CPPIE_4 = '4',
    CPPIE_5 = '5',
    CPPIE_6 = '6',
    CPPIE_7 = '7',
    CPPIE_8 = '8',
    CPPIE_9 = '9',
    CPPIE_COLON = ':',
    CPPIE_SEMICOLON = ';',
    CPPIE_LESS = '<',
    CPPIE_EQUALS = '=',
    CPPIE_GREATER = '>',
    CPPIE_QUESTION = '?',
    CPPIE_AT = '@',
    /* 
       Skip uppercase letters
     */
    CPPIE_LEFTBRACKET = '[',
    CPPIE_BACKSLASH = '\\',
    CPPIE_RIGHTBRACKET = ']',
    CPPIE_CARET = '^',
    CPPIE_UNDERSCORE = '_',
    CPPIE_BACKQUOTE = '`',
    CPPIE_a = 'a',
    CPPIE_b = 'b',
    CPPIE_c = 'c',
    CPPIE_d = 'd',
    CPPIE_e = 'e',
    CPPIE_f = 'f',
    CPPIE_g = 'g',
    CPPIE_h = 'h',
    CPPIE_i = 'i',
    CPPIE_j = 'j',
    CPPIE_k = 'k',
    CPPIE_l = 'l',
    CPPIE_m = 'm',
    CPPIE_n = 'n',
    CPPIE_o = 'o',
    CPPIE_p = 'p',
    CPPIE_q = 'q',
    CPPIE_r = 'r',
    CPPIE_s = 's',
    CPPIE_t = 't',
    CPPIE_u = 'u',
    CPPIE_v = 'v',
    CPPIE_w = 'w',
    CPPIE_x = 'x',
    CPPIE_y = 'y',
    CPPIE_z = 'z',

    CPPIE_CAPSLOCK = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CAPSLOCK),

    CPPIE_F1 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F1),
    CPPIE_F2 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F2),
    CPPIE_F3 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F3),
    CPPIE_F4 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F4),
    CPPIE_F5 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F5),
    CPPIE_F6 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F6),
    CPPIE_F7 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F7),
    CPPIE_F8 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F8),
    CPPIE_F9 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F9),
    CPPIE_F10 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F10),
    CPPIE_F11 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F11),
    CPPIE_F12 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F12),

    CPPIE_PRINTSCREEN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_PRINTSCREEN),
    CPPIE_SCROLLLOCK = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_SCROLLLOCK),
    CPPIE_PAUSE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_PAUSE),
    CPPIE_INSERT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_INSERT),
    CPPIE_HOME = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_HOME),
    CPPIE_PAGEUP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_PAGEUP),
    CPPIE_DELETE = '\177',
    CPPIE_END = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_END),
    CPPIE_PAGEDOWN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_PAGEDOWN),
    CPPIE_RIGHT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_RIGHT),
    CPPIE_LEFT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_LEFT),
    CPPIE_DOWN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_DOWN),
    CPPIE_UP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_UP),

    CPPIE_NUMLOCKCLEAR = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_NUMLOCKCLEAR),
    CPPIE_KP_DIVIDE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_DIVIDE),
    CPPIE_KP_MULTIPLY = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MULTIPLY),
    CPPIE_KP_MINUS = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MINUS),
    CPPIE_KP_PLUS = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_PLUS),
    CPPIE_KP_ENTER = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_ENTER),
    CPPIE_KP_1 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_1),
    CPPIE_KP_2 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_2),
    CPPIE_KP_3 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_3),
    CPPIE_KP_4 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_4),
    CPPIE_KP_5 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_5),
    CPPIE_KP_6 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_6),
    CPPIE_KP_7 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_7),
    CPPIE_KP_8 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_8),
    CPPIE_KP_9 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_9),
    CPPIE_KP_0 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_0),
    CPPIE_KP_PERIOD = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_PERIOD),

    CPPIE_APPLICATION = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_APPLICATION),
    CPPIE_POWER = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_POWER),
    CPPIE_KP_EQUALS = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_EQUALS),
    CPPIE_F13 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F13),
    CPPIE_F14 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F14),
    CPPIE_F15 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F15),
    CPPIE_F16 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F16),
    CPPIE_F17 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F17),
    CPPIE_F18 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F18),
    CPPIE_F19 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F19),
    CPPIE_F20 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F20),
    CPPIE_F21 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F21),
    CPPIE_F22 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F22),
    CPPIE_F23 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F23),
    CPPIE_F24 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_F24),
    CPPIE_EXECUTE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_EXECUTE),
    CPPIE_HELP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_HELP),
    CPPIE_MENU = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_MENU),
    CPPIE_SELECT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_SELECT),
    CPPIE_STOP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_STOP),
    CPPIE_AGAIN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AGAIN),
    CPPIE_UNDO = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_UNDO),
    CPPIE_CUT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CUT),
    CPPIE_COPY = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_COPY),
    CPPIE_PASTE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_PASTE),
    CPPIE_FIND = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_FIND),
    CPPIE_MUTE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_MUTE),
    CPPIE_VOLUMEUP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_VOLUMEUP),
    CPPIE_VOLUMEDOWN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_VOLUMEDOWN),
    CPPIE_KP_COMMA = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_COMMA),
    CPPIE_KP_EQUALSAS400 =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_EQUALSAS400),

    CPPIE_ALTERASE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_ALTERASE),
    CPPIE_SYSREQ = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_SYSREQ),
    CPPIE_CANCEL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CANCEL),
    CPPIE_CLEAR = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CLEAR),
    CPPIE_PRIOR = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_PRIOR),
    CPPIE_RETURN2 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_RETURN2),
    CPPIE_SEPARATOR = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_SEPARATOR),
    CPPIE_OUT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_OUT),
    CPPIE_OPER = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_OPER),
    CPPIE_CLEARAGAIN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CLEARAGAIN),
    CPPIE_CRSEL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CRSEL),
    CPPIE_EXSEL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_EXSEL),

    CPPIE_KP_00 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_00),
    CPPIE_KP_000 = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_000),
    CPPIE_THOUSANDSSEPARATOR =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_THOUSANDSSEPARATOR),
    CPPIE_DECIMALSEPARATOR =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_DECIMALSEPARATOR),
    CPPIE_CURRENCYUNIT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CURRENCYUNIT),
    CPPIE_CURRENCYSUBUNIT =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CURRENCYSUBUNIT),
    CPPIE_KP_LEFTPAREN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_LEFTPAREN),
    CPPIE_KP_RIGHTPAREN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_RIGHTPAREN),
    CPPIE_KP_LEFTBRACE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_LEFTBRACE),
    CPPIE_KP_RIGHTBRACE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_RIGHTBRACE),
    CPPIE_KP_TAB = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_TAB),
    CPPIE_KP_BACKSPACE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_BACKSPACE),
    CPPIE_KP_A = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_A),
    CPPIE_KP_B = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_B),
    CPPIE_KP_C = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_C),
    CPPIE_KP_D = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_D),
    CPPIE_KP_E = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_E),
    CPPIE_KP_F = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_F),
    CPPIE_KP_XOR = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_XOR),
    CPPIE_KP_POWER = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_POWER),
    CPPIE_KP_PERCENT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_PERCENT),
    CPPIE_KP_LESS = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_LESS),
    CPPIE_KP_GREATER = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_GREATER),
    CPPIE_KP_AMPERSAND = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_AMPERSAND),
    CPPIE_KP_DBLAMPERSAND =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_DBLAMPERSAND),
    CPPIE_KP_VERTICALBAR =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_VERTICALBAR),
    CPPIE_KP_DBLVERTICALBAR =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_DBLVERTICALBAR),
    CPPIE_KP_COLON = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_COLON),
    CPPIE_KP_HASH = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_HASH),
    CPPIE_KP_SPACE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_SPACE),
    CPPIE_KP_AT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_AT),
    CPPIE_KP_EXCLAM = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_EXCLAM),
    CPPIE_KP_MEMSTORE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MEMSTORE),
    CPPIE_KP_MEMRECALL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MEMRECALL),
    CPPIE_KP_MEMCLEAR = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MEMCLEAR),
    CPPIE_KP_MEMADD = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MEMADD),
    CPPIE_KP_MEMSUBTRACT =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MEMSUBTRACT),
    CPPIE_KP_MEMMULTIPLY =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MEMMULTIPLY),
    CPPIE_KP_MEMDIVIDE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_MEMDIVIDE),
    CPPIE_KP_PLUSMINUS = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_PLUSMINUS),
    CPPIE_KP_CLEAR = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_CLEAR),
    CPPIE_KP_CLEARENTRY = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_CLEARENTRY),
    CPPIE_KP_BINARY = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_BINARY),
    CPPIE_KP_OCTAL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_OCTAL),
    CPPIE_KP_DECIMAL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_DECIMAL),
    CPPIE_KP_HEXADECIMAL =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KP_HEXADECIMAL),

    CPPIE_LCTRL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_LCTRL),
    CPPIE_LSHIFT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_LSHIFT),
    CPPIE_LALT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_LALT),
    CPPIE_LGUI = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_LGUI),
    CPPIE_RCTRL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_RCTRL),
    CPPIE_RSHIFT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_RSHIFT),
    CPPIE_RALT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_RALT),
    CPPIE_RGUI = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_RGUI),

    CPPIE_MODE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_MODE),

    CPPIE_AUDIONEXT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AUDIONEXT),
    CPPIE_AUDIOPREV = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AUDIOPREV),
    CPPIE_AUDIOSTOP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AUDIOSTOP),
    CPPIE_AUDIOPLAY = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AUDIOPLAY),
    CPPIE_AUDIOMUTE = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AUDIOMUTE),
    CPPIE_MEDIASELECT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_MEDIASELECT),
    CPPIE_WWW = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_WWW),
    CPPIE_MAIL = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_MAIL),
    CPPIE_CALCULATOR = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_CALCULATOR),
    CPPIE_COMPUTER = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_COMPUTER),
    CPPIE_AC_SEARCH = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AC_SEARCH),
    CPPIE_AC_HOME = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AC_HOME),
    CPPIE_AC_BACK = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AC_BACK),
    CPPIE_AC_FORWARD = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AC_FORWARD),
    CPPIE_AC_STOP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AC_STOP),
    CPPIE_AC_REFRESH = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AC_REFRESH),
    CPPIE_AC_BOOKMARKS = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_AC_BOOKMARKS),

    CPPIE_BRIGHTNESSDOWN =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_BRIGHTNESSDOWN),
    CPPIE_BRIGHTNESSUP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_BRIGHTNESSUP),
    CPPIE_DISPLAYSWITCH = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_DISPLAYSWITCH),
    CPPIE_KBDILLUMTOGGLE =
        CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KBDILLUMTOGGLE),
    CPPIE_KBDILLUMDOWN = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KBDILLUMDOWN),
    CPPIE_KBDILLUMUP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_KBDILLUMUP),
    CPPIE_EJECT = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_EJECT),
    CPPIE_SLEEP = CPPIE_SCANCODE_TO_KEYCODE(CPPIE_SCANCODE_SLEEP)
};