#pragma once

#define CPPIE_WINDOWEVENT_FOCUS_GAIN	1101
#define CPPIE_WINDOWEVENT_FOCUS_LOST	1102

#define CPPIE_WINDOWEVENT_MOUSE_ENTER	1201
#define CPPIE_WINDOWEVENT_MOUSE_LEAVE	1202

namespace Cppie{

};